version: '3.8'

services:
  boss-challenge-bot:
    image: ghcr.io/ainsley2007/boss-challenge:latest
    container_name: boss-challenge-bot
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    volumes:
      - ./data:/app/data
    labels:
      - com.centurylinklabs.watchtower.enable=true
